name: Test Pipeline

on:
  push:
    branches: [ main, dev, feature/pipeline ]
  pull_request:
    branches: [ main, dev ]

env:
  PYTHON_VERSION: '3.12'

jobs:
  test:
    name: Unit Tests en Integratie Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest flake8 autopep8 pytest-asyncio

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

      - name: Run Flake8
        run: flake8 . --max-line-length=120 --exclude=venv,__pycache__ --ignore=E501,W503,W504.E203,E402

      - name: Format check
        run: autopep8 --diff --recursive . | tee check.diff

      - name: Run Tests
        run: pytest tests/ --disable-warnings

