name: Test Pipeline

on:
  push:
    branches: [ main, dev, TestBranch ]
  pull_request:
    branches: [ main, dev ]

env:
  PYTHON_VERSION: '3.12'

jobs:
  test:
    name: Unit Tests en Integratie Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -U crawl4ai
          pip install pytest autopep8 pytest-asyncio
          playwright install

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

      - name: Format check
        run: autopep8 --diff --recursive . | tee check.diff

      - name: Run Tests
        run: pytest tests/ --disable-warnings

  notify:
    name: Notify Discord
    runs-on: ubuntu-latest
    needs: [test]
    if: always()

    steps:
      - name: Notify Discord on success
        if: ${{ success() }}
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          message: "✅ CI/CD pipeline geslaagd voor ${{ github.repository }}!"

      - name: Notify Discord on failure
        if: ${{ failure() }}
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          message: "❌ CI/CD pipeline gefaald voor ${{ github.repository }}! Check de logs: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
