name: Test Pipeline

on:
  push:
    branches: [ main, dev, TestBranch ]
  pull_request:
    branches: [ main, dev ]

env:
  PYTHON_VERSION: '3.12'

jobs:
  test:
    name: Unit Tests en Integratie Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3 libnspr4 libgbm1 libasound2

      - name: List files
        run: ls -R

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
          pip install -U crawl4ai
          pip install pytest autopep8 pytest-asyncio
          playwright install

      - name: Verify Playwright installation
        run: python -m playwright install --with-deps chromium

      - name: Debug Python environment
        run: |
          python -c "import sys; print(sys.path)"
          pip list

      - name: Test Crawlscraper import
        run: python -c "import Crawlscraper; import crawl4ai; print(crawl4ai.__version__)"

      - name: Format check
        run: autopep8 --diff --recursive . | tee check.diff

      - name: Run Tests
        run: pytest tests/

    notify:
      name: Notify Discord
      runs-on: ubuntu-latest
      needs: [test]
      if: always()

      steps:
        - name: Notify Discord on success
          if: ${{ success() }}
          uses: appleboy/discord-action@master
          with:
            webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
            webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
            message: "✅ CI/CD pipeline geslaagd voor ${{ github.repository }}!"

        - name: Notify Discord on failure
          if: ${{ failure() }}
          uses: appleboy/discord-action@master
          with:
            webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
            webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
            message: "❌ CI/CD pipeline gefaald voor ${{ github.repository }}! Check de logs: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"